### PR TITLE
Renamed our repo to 3DStreamingToolkit

### PR DESCRIPTION
**Pull request by anderm**
## Checklist
- [x] **I have read the [contribution guidelines](../blob/master/CONTRIBUTING.md).**
- [x] Title of the pull request is clear and informative.
- [x] If applicable, the code is properly documented.
- [x] The code builds without any errors.
- [x] All unit and integration tests pass.

## Description
Renamed our repo to 3DStreamingToolkit and updated all instances of 3dtoolkit to new name. 

## Related Issues and PRs
#218

### CODE REVIEW

**Comment by phongcao** [comment]
We're still using **3dtoolkit** in _CONTRIBUTING.md_, _ISSUE_TEMPLATE.md_ and _PULL_REQUEST_TEMPLATE.md_. Also, should we also need to rename js-3dtoolkit repo?

**Comment by anderm** [comment]
@phongcao Great catch! I updated the name across our CONTRIBUTING.md, ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md. For js-3dtoolkit, I want to rename it but I am currently blocked as I am not an admin of that repo. I created a new issue for that #250, so we don't block this PR

**Comment by phongcao** [comment]
@anderm The [contribution guidelines](https://github.com/CatalystCode/3DStreamingToolkit/CONTRIBUTING.md) returns 'Not Found'. Do you know why?

**Comment by anderm** [comment]
@phongcao looks like our PULL_REQUEST_TEMPLATE had a wrong relative path to contribution guidelines. It is working now [contribution guidelines](../blob/master/CONTRIBUTING.md)

**Comment by anderm** [comment]
@phongcao thanks for the review! CI builds are all green and officially switched to gtest. Merging

**Pull request merged**
