### PR TITLE
add vcpkg, migrate existing tests to gtest

### PR DESCRIPTION
**Pull request by bengreenier**
## Checklist
***This checklist is used to make sure that common guidelines for a pull request are followed.***

- [x] Title of the pull request is clear and informative.
- [x] If applicable, the code is properly documented.
- [x] The code builds without any errors.
- [x] All unit and integration tests pass.

## Description

This migrates our project config and test frameworks to use gtest instead of mstest as it is preferable for our needs. This also includes a dependency on [vcpkg.nuget](https://github.com/bengreenier/vcpkg.nuget) so that we can easily consume `gtest` as a dependency, but also to set us up for future success using `vcpkg` to manage our deps.

## Related Issues and PRs

+ addresses #225

### CODE REVIEW

**Comment by bengreenier** [comment]
I want to see if the ci build knows what to do here, my guess is it will not run the tests and i'll need to update that as well.

**Comment by bengreenier** [comment]
There are likely some collisions here with the #178 work, as this also requires projects @ compiler v141. hopefully the collisions are minor 😅

**Comment by anderm** [comment]
@bengreenier I am ok with adding the testing info to `CONTRIBUTING.md` for now. This might change once we finish #223. If our focus for this repo is to enable integration with other rendering engines, then it makes sense to specify testing on the main `README` as well, not only when contributing back. This will make it easier for developers to get started, understand all the custom parts and integrate our plugin.

**Comment by anderm** [comment]
We will merge this PR as soon as #229 is merged into master and all conflicts are resolved. Awesome work, Ben 💪

**Comment by bengreenier** [comment]
looks like a double import error, didn't occur locally for me. will investigate in the am 🕙 

the `-static` vcpkg triplet fixes our `gtest` linkage issue though, which is great! 🚀

**Comment by bengreenier** [comment]
build is green now! fixing an issue with running gtests in ci, as well as this `NativeServer` test issue:

```
2018-06-11T15:40:48.8135548Z ##[error][OpenH264] this = 0x0000021F36A43C30, Warning:WelsEncoderEncodeExt()MinCr Checking,codec bitstream size is larger than Level limitation
```

Once that's done we can `update branch` and :shipit:

**Comment by bengreenier** [comment]
gtest works in ci. This is good to go. Post merge we'll address the ci build changes to the official build #241 will track that work.

> Note: i've queued a build on `-gtest` ci that should go green (was only failing due to azure blob upload which is known to be broken temporarily) but am going to 🛌  hopefully after i 😴 the build is ✔️

**Comment by bengreenier** [comment]
ok the build is broken again. i am wondering if this is going to be an ongoing transient issue

**Comment by bengreenier** [comment]
Looks like ninja is failing in ci now.

**Comment by phongcao** [comment]
I've resolved all conflicts with latest master and converted all of our tests to gtest.

**Comment by anderm** [comment]
@phongcao @bengreenier All tests are green! I started the gtest CI build and that passed as well. We are good to go, great work guys!

**Pull request merged**
